stages:
  - build

rust-nightly:
  stage: build
  image: git.mintendo-programmer.de:5050/gba/industry-advance:latest
  script:
    # Run tests
    - cargo make test
    # Create artifact
    - cargo make
  artifacts:
    paths:
      - target/industry-advance.gba
