stages:
  - build

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - apt update
    - apt install binutils-arm-none-eabi
    - cargo install cargo-make cargo-xbuild
    - rustup component add rust-src
    - cargo make --verbose
    - cargo test --verbose
  artifacts:
    paths:
      - target/industry-advance.gba
#  allow_failure: true
