stages:
  - build

rust-nightly:
  stage: build
  image: git.mintendo-programmer.de:5050/gba/industry-advance:latest
  script:
    - cargo make --verbose
    # - cargo test --verbose
  artifacts:
    paths:
      - target/industry-advance.gba
#  allow_failure: true
