[package]
name = "industry-advance"
version = "0.1.0"
authors = ["casept <davids.paskevics@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[dependencies]
# TODO: Revert to mintendo-programmer server once certificate is fixed
#gba = { git = "https://git.mintendo-programmer.de/gba/gba", branch = "frickel" }
gba = { git = "https://gitlab.spline.inf.fu-berlin.de/gba/gba", branch = "frickel" }
voladdress = "*"
typenum = "*"
linked_list_allocator = {version = "*", default_features = false} # Spinlock unusable due to lack of HW support for atomics
ansi_rgb = "*"
tiny_ecs = {git = "https://gitlab.com/casept/tiny_ecs", branch = "no_std", features = ["no_std"]}
