[config]
skip_core_tasks = true

[tasks.create-target-dir]
command = "mkdir"
args = ["-p", "./target"]

[tasks.assets]
command = "python3"
args = ["./convert_assets.py"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.build-debug]
command = "cargo"
args = ["build"]

[tasks.pack-rom]
dependencies = ["build"]
command = "arm-none-eabi-objcopy"
args = ["-O", "binary", "target/thumbv4t-nintendo-none-eabi/release/industry-advance", "target/industry-advance.gba"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-release]
command = "cargo"
args = ["test", "--release"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.run]
dependencies = ["build", "pack-rom"]
command = "mgba"
args = ["--log-level=-1", "target/industry-advance.gba"]

[tasks.run-qt]
dependencies = ["build", "pack-rom"]
command = "mgba-qt"
args = ["--log-level=-1", "target/industry-advance.gba"]

[tasks.justrelease]
dependencies = ["build", "pack-rom"]

[tasks.build-all]
dependencies = ["build", "pack-rom"]

[tasks.default]
alias = "build-all"

[tasks.debug-gdb]
dependencies = ["build-debug"]
command = "mgba-qt"
args = ["--log-level=2047", "./target/thumbv4t-nintendo-none-eabi/debug/industry-advance", "-g"]

[tasks.debug]
dependencies = ["build-debug"]
command = "mgba-qt"
args = ["--log-level=2047", "./target/thumbv4t-nintendo-none-eabi/debug/industry-advance"]

[tasks.docs]
command = "cargo"
args = ["doc", "--open"]
