[config]
skip_core_tasks = true

[tasks.create-target-dir]
command = "mkdir"
args = ["-p", "./target"]

[tasks.assemble]
dependencies = ["create-target-dir"]
command = "arm-none-eabi-as"
args = ["crt0.s", "-o", "target/crt0.o"]

[tasks.assets]
command = "python3"
args = ["./convert-assets.py"]

[tasks.build]
dependencies = ["assemble"]
command = "cargo"
args = ["build", "-Z", "build-std=core,alloc", "--target", "thumbv4-none-agb.json", "--release"]

[tasks.build-debug]
dependencies = ["assemble"]
command = "cargo"
args = ["build", "-Z", "build-std=core,alloc", "--target", "thumbv4-none-agb.json"]

[tasks.pack-rom]
dependencies = ["build"]
command = "arm-none-eabi-objcopy"
args = ["-O", "binary", "target/thumbv4-none-agb/release/industry-advance", "target/industry-advance.gba"]

[tasks.test]
dependencies = ["assemble"]
command = "cargo"
args = ["test", "-Z", "build-std=core,alloc", "--target", "thumbv4-none-agb.json"]

[tasks.clippy]
dependencies = ["assemble"]
command = "cargo"
args = ["clippy", "-Z", "build-std=core,alloc", "--target", "thumbv4-none-agb.json"]

[tasks.run]
dependencies = ["build", "pack-rom"]
command = "mgba"
args = ["--log-level=-1", "target/industry-advance.gba"]

[tasks.run-qt]
dependencies = ["build", "pack-rom"]
command = "/usr/bin/mgba-qt"
args = ["--log-level=-1", "target/industry-advance.gba"]

[tasks.justrelease]
dependencies = ["build", "pack-rom"]

[tasks.build-all]
dependencies = ["build", "pack-rom"]

[tasks.default]
alias = "build-all"

[tasks.debug-gdb]
dependencies = ["build-debug"]
command = "/usr/bin/mgba-qt"
args = ["--log-level=2047", "./target/thumbv4-none-agb/debug/industry-advance", "-g"]

[tasks.debug]
dependencies = ["build-debug"]
command = "/usr/bin/mgba-qt"
args = ["--log-level=2047", "./target/thumbv4-none-agb/debug/industry-advance"]

[tasks.docs]
dependencies = ["assemble"]
command = "cargo"
args = ["doc", "--open", "-Z", "build-std=core,alloc", "--target", "thumbv4-none-agb.json"]
