[build]
target = "thumbv4t-nintendo-none-eabi.json"

[unstable]
build-std = ["core", "alloc"]

[target.thumbv4t-nintendo-none-eabi]
rustflags = ["-Clink-arg=-Tlinker.ld"]
runner = ["bash", "./runtests.sh"]
